const topics = [
	'comfort food',
	'your favorite season',
	'a perfect weekend',
	'a childhood hobby',
	'a dream travel destination',
	'a morning routine',
	'a favorite movie',
	'a memorable song',
	'a favorite book',
	'the best advice you have received',
	'a cozy place',
	'a hidden talent',
	'a favorite dessert',
	'a dream job',
	'a favorite game',
	'a favorite holiday',
	'a proud achievement',
	'a funny memory',
	'a favorite app',
	'a favorite teacher',
	'a personal goal',
	'a favorite quote',
	'an ideal vacation',
	'a favorite drink',
	'a creative project',
	'a favorite tradition',
	'the best gift you have received',
	'a favorite color',
	'a favorite meal',
	'a rainy day activity',
	'a sunny day activity',
	'a favorite childhood show',
	'a skill you want to learn',
	'a favorite place in your town',
	'the best concert or live event you have attended',
	'a favorite restaurant',
	'a dream house',
	'a favorite board game',
	'a favorite video game',
	'a favorite sport',
	'a relaxing activity',
	'a favorite smell',
	'a favorite snack',
	'a meaningful friendship',
	'a family tradition',
	'a favorite school subject',
	'the best purchase you have made',
	'a favorite outfit',
	'a perfect birthday',
	'a favorite school memory',
	'a dream collaboration',
	'a favorite playlist',
	'a favorite podcast',
	'a helpful habit',
	'a favorite way to celebrate',
	'your favorite thing about today',
	'a challenge you overcame',
	'a favorite room',
	'a favorite time of day',
	'a weekend ritual',
	'a favorite museum',
	'a favorite fictional world',
	'a favorite character',
	'a favorite recipe',
	'a favorite cafe',
	'a dream skill',
	'a favorite photo',
	'the best surprise you have had',
	'a favorite city',
	'a favorite nature spot',
	'a favorite piece of technology',
	'a favorite childhood toy',
	'something you are grateful for',
];

const questionTemplates = [
	topic => `What comes to mind when you think about ${topic}, and why?`,
	topic => `What is one memory you connect with ${topic}?`,
	topic => `How has your opinion about ${topic} changed over time?`,
	topic => `What would you recommend to someone curious about ${topic}?`,
	topic => `What is something underrated about ${topic}?`,
];

const questions = topics.flatMap(topic => questionTemplates.map(template => template(topic)));

if (questions.length !== 365) {
	throw new Error(`QOTD questions must contain exactly 365 questions, found ${questions.length}.`);
}

module.exports = questions;
